### ISSUE TITLE
Can not Build With Embarcadero RAD Studio XE C++ Builder

### ISSUE THREAD

**Issue by motapratik** [orocos-toolchain/log4cpp#15]
It is giving below Error
=========================

Checking project dependencies...
Building log4cpp.cbproj (Debug, Win32)
bcc32 command line for "..\..\src\Appender.cpp"
  c:\program files (x86)\embarcadero\rad studio\8.0\bin\bcc32.exe -D_DEBUG;NO_STRICT;LOG4CPP_HAS_DLL;LOG4CPP_BUILD_DLL;WIN32;;NO_STRICT;LOG4CPP_HAS_DLL;
  LOG4CPP_BUILD_DLL;WIN32; -D;_RTLDLL;_NO_VCL -nDebug_Build -I..\..\src;"c:\program files (x86)\embarcadero\rad studio\8.0\include";..\..\include;
  "c:\program files (x86)\embarcadero\rad studio\8.0\include\dinkumware";..\..\src;"C:\Program Files (x86)\Embarcadero\RAD 
  Studio\8.0\include\boost_1_39\boost\tr1\tr1";"C:\Program Files (x86)\Embarcadero\RAD Studio\8.0\include\boost_1_39";"c:\program files 
  (x86)\embarcadero\rad studio\8.0\include";"c:\program files (x86)\embarcadero\rad studio\8.0\include\windows\crtl";"c:\program files 
  (x86)\embarcadero\rad studio\8.0\include\dinkumware";"c:\program files (x86)\embarcadero\rad studio\8.0\include\windows\sdk";"c:\program files 
  (x86)\embarcadero\rad studio\8.0\include\windows\rtl";"c:\program files (x86)\embarcadero\rad studio\8.0\include\windows\vcl";"C:\Program Files 
  (x86)\Raize\CS4\Lib\RS-XE";"c:\program files (x86)\embarcadero\rad studio\8.0\RaveReports\Lib";"C:\Program Files\Developer 
  Express.VCL\Library\CBuilder15" -y -c -tD -tM -C8 -oDebug_Build\Appender.obj -Od -v -vi- -H=Debug_Build\log4cpp.pch -H  -tWM -Vx -r- -k -tWD -Ve -k 
  ..\..\src\Appender.cpp 
[BCC32 Warning] Appender.hh(164): W8058 Cannot create pre-compiled header: initialized data in header
[BCC32 Error] Appender.cpp(23): E2247 'Appender::_deleteAllAppenders()' is not accessible
[BCC32 Error] Appender.cpp(34): E2247 'Appender::_appenderMapStorageInstance' is not accessible
[BCC32 Error] Appender.cpp(42): E2247 'Appender::_appenderMapStorageInstance' is not accessible
[BCC32 Warning] Appender.cpp(113): W8004 'allAppenders' is assigned a value that is never used
Failed
Elapsed time: 00:00:00.4

**Comment by meyerj** [comment]
This GitHub project is a fork of the upstream repository at SourceForge, https://sourceforge.net/projects/log4cpp/, to be used within the [Orocos](http://www.orocos.org) project. It adds cmake build support and some minor patches to enable logging in real-time, output thread IDs or more precise time stamps.

The issue you reported seems not related to any of these changes. Do you build log4cpp using cmake? Do you use log4cpp in an Orocos context?

If not and this issue is still relevant, please create a bug report in the [upstream issue tracker](https://sourceforge.net/p/log4cpp/bugs/) instead.
